"""initial schema

Revision ID: 6d7e19e4445d
Revises:
Create Date: 2026-09-27 07:29:12.460823

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6d7e19e4445d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "children",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("rate", sa.Integer(), server_default="10", nullable=False),
        sa.Column("cap_lari", sa.Integer(), server_default="15", nullable=False),
        sa.Column("show_hint", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_children")),
    )
    op.create_table(
        "parents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parents")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_parents_telegram_id")),
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("title_ru", sa.String(length=100), nullable=False),
        sa.Column("title_ka", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=16), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("slug", name=op.f("uq_topics_slug")),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_devices_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_devices_token_hash")),
    )
    op.create_index(op.f("ix_devices_child_id"), "devices", ["child_id"], unique=False)
    op.create_table(
        "pair_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_pair_codes_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["parents.id"],
            name=op.f("fk_pair_codes_parent_id_parents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pair_codes")),
        sa.UniqueConstraint("code", name=op.f("uq_pair_codes_code")),
    )
    op.create_table(
        "parent_children",
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_parent_children_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["parents.id"],
            name=op.f("fk_parent_children_parent_id_parents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("parent_id", "child_id", name=op.f("pk_parent_children")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("study_date", sa.Date(), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_sessions_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_sessions_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_child_id"), "sessions", ["child_id"], unique=False)
    op.create_table(
        "weeks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("coins", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "paid", name="week_status"),
            server_default="open",
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lari_paid", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("rate_snapshot", sa.Integer(), nullable=True),
        sa.Column("cap_snapshot", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_weeks_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weeks")),
        sa.UniqueConstraint("child_id", "week_start", name=op.f("uq_weeks_child_id_week_start")),
    )
    op.create_index(op.f("ix_weeks_child_id"), "weeks", ["child_id"], unique=False)
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("ka", sa.String(length=100), nullable=False),
        sa.Column("tr", sa.String(length=100), nullable=False),
        sa.Column("ru", sa.String(length=100), nullable=False),
        sa.Column(
            "image_kind", sa.Enum("emoji", "color", "file", name="image_kind"), nullable=False
        ),
        sa.Column("image_value", sa.String(length=255), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_words_topic_id_topics"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_words")),
        sa.UniqueConstraint("topic_id", "slug", name=op.f("uq_words_topic_id_slug")),
    )
    op.create_index(op.f("ix_words_topic_id"), "words", ["topic_id"], unique=False)
    op.create_table(
        "answers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("client_answer_id", sa.UUID(), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("coins_gained", sa.Integer(), nullable=False),
        sa.Column("word_learned", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_answers_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["word_id"], ["words.id"], name=op.f("fk_answers_word_id_words"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answers")),
        sa.UniqueConstraint("client_answer_id", name=op.f("uq_answers_client_answer_id")),
    )
    op.create_index(op.f("ix_answers_session_id"), "answers", ["session_id"], unique=False)
    op.create_table(
        "word_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("last_correct_date", sa.Date(), nullable=True),
        sa.Column("introduced", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("learned_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("stage BETWEEN 0 AND 3", name=op.f("ck_word_progress_stage_range")),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_word_progress_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
            name=op.f("fk_word_progress_word_id_words"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_word_progress")),
        sa.UniqueConstraint("child_id", "word_id", name=op.f("uq_word_progress_child_id_word_id")),
    )
    op.create_index(op.f("ix_word_progress_child_id"), "word_progress", ["child_id"], unique=False)
    op.create_table(
        "coin_ledger",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("week_id", sa.Integer(), nullable=False),
        sa.Column("answer_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Enum("answer", "word_learned", name="coin_reason"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
            name=op.f("fk_coin_ledger_answer_id_answers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_coin_ledger_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["week_id"], ["weeks.id"], name=op.f("fk_coin_ledger_week_id_weeks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coin_ledger")),
    )
    op.create_index(op.f("ix_coin_ledger_child_id"), "coin_ledger", ["child_id"], unique=False)
    op.create_index(op.f("ix_coin_ledger_week_id"), "coin_ledger", ["week_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_coin_ledger_week_id"), table_name="coin_ledger")
    op.drop_index(op.f("ix_coin_ledger_child_id"), table_name="coin_ledger")
    op.drop_table("coin_ledger")
    op.drop_index(op.f("ix_word_progress_child_id"), table_name="word_progress")
    op.drop_table("word_progress")
    op.drop_index(op.f("ix_answers_session_id"), table_name="answers")
    op.drop_table("answers")
    op.drop_index(op.f("ix_words_topic_id"), table_name="words")
    op.drop_table("words")
    op.drop_index(op.f("ix_weeks_child_id"), table_name="weeks")
    op.drop_table("weeks")
    op.drop_index(op.f("ix_sessions_child_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("parent_children")
    op.drop_table("pair_codes")
    op.drop_index(op.f("ix_devices_child_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_table("topics")
    op.drop_table("parents")
    op.drop_table("children")
    # ### end Alembic commands ###
    # Autogenerate does not drop PostgreSQL enum types created by sa.Enum.
    for enum_name in ("coin_reason", "image_kind", "week_status"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
