import type { WordOut } from './types'

const key = (w: WordOut) => `${w.topic_slug}/${w.slug}`

/** Spoken quiz feedback, generated by scripts/gen_tts.py into media/audio/ui/. */
export type Phrase = 'correct' | 'wrong'
const PHRASES: Phrase[] = ['correct', 'wrong']
const phraseKey = (p: Phrase) => `ui/${p}`

/** Plays word audio from /media, falling back to speech synthesis when a file is missing. */
export class Speaker {
  private cache = new Map<string, HTMLAudioElement>()
  private missing = new Set<string>()
  private unlocked = false

  /** Create and start loading elements for every word of the session and the feedback phrases. */
  preload(words: WordOut[]): void {
    for (const w of words) this.add(key(w), w.audio_url)
    for (const p of PHRASES) this.add(phraseKey(p), `/media/audio/${phraseKey(p)}.mp3`)
  }

  private add(k: string, url: string): void {
    if (this.cache.has(k)) return
    const audio = new Audio(url)
    audio.preload = 'auto'
    audio.addEventListener('error', () => this.missing.add(k))
    this.cache.set(k, audio)
  }

  /**
   * iOS allows programmatic playback only for elements that were once played
   * from a user gesture. Call this inside the tap that starts the lesson.
   */
  unlock(): void {
    if (this.unlocked) return
    this.unlocked = true
    for (const audio of this.cache.values()) {
      audio.muted = true
      audio
        .play()
        .then(() => {
          audio.pause()
          audio.currentTime = 0
        })
        .catch(() => {})
        .finally(() => {
          audio.muted = false
        })
    }
  }

  /** Start the word's audio; resolves once playback has started. */
  async play(word: WordOut): Promise<void> {
    this.stop()
    if (await this.start(key(word))) return
    speak(word)
  }

  /** Play the word's audio to the end (about a second), so a phrase can follow it. */
  async playThrough(word: WordOut): Promise<void> {
    this.stop()
    const audio = this.cache.get(key(word))
    if (audio && (await this.start(key(word)))) {
      await ended(audio)
      return
    }
    speak(word)
  }

  /** Spoken feedback after an answer. Silent when the file is missing: the toast still shows. */
  async phrase(name: Phrase): Promise<void> {
    this.stop()
    const audio = this.cache.get(phraseKey(name))
    if (audio && (await this.start(phraseKey(name)))) await ended(audio)
  }

  private async start(k: string): Promise<boolean> {
    const audio = this.cache.get(k)
    if (!audio || this.missing.has(k)) return false
    try {
      audio.currentTime = 0
      await audio.play()
      return true
    } catch {
      return false
    }
  }

  stop(): void {
    for (const audio of this.cache.values()) {
      if (!audio.paused) audio.pause()
    }
    try {
      speechSynthesis.cancel()
    } catch {
      /* no synthesis */
    }
  }
}

/** Resolves when the element stops (ended, paused by stop(), or failed); never hangs. */
function ended(audio: HTMLAudioElement): Promise<void> {
  if (audio.paused || audio.ended) return Promise.resolve()
  return new Promise((resolve) => {
    const done = () => {
      for (const ev of ['ended', 'pause', 'error']) audio.removeEventListener(ev, done)
      clearTimeout(guard)
      resolve()
    }
    for (const ev of ['ended', 'pause', 'error']) audio.addEventListener(ev, done)
    const guard = setTimeout(done, 4000)
  })
}

let voices: SpeechSynthesisVoice[] = []
function loadVoices() {
  try {
    voices = speechSynthesis.getVoices() ?? []
  } catch {
    voices = []
  }
}
try {
  loadVoices()
  speechSynthesis.addEventListener('voiceschanged', loadVoices)
} catch {
  /* no speechSynthesis in this browser */
}

function speak(word: WordOut): void {
  try {
    const ka = voices.find((v) => v.lang.toLowerCase().startsWith('ka'))
    const utterance = new SpeechSynthesisUtterance(ka ? word.ka : word.tr)
    if (ka) {
      utterance.voice = ka
      utterance.lang = ka.lang
    } else {
      const ru = voices.find((v) => v.lang.toLowerCase().startsWith('ru'))
      if (ru) utterance.voice = ru
      utterance.lang = ru?.lang ?? 'ru-RU'
    }
    utterance.rate = 0.75
    speechSynthesis.speak(utterance)
  } catch {
    /* nothing to fall back to */
  }
}
